In [6]:
## ###`Q-2:Write a Pandas program to add, subtract, multiply and divide two Pandas Series.

import pandas as pd

index = ('benzene', 'acetone', 'toluene', 'pentane', 'ether', 'ethanol', 'methanol')
table = pd.Series([80, 56, 111, 36, 35, 78, 65], index = index)
print(table)

index = ('A', 'B', 'C', 'D', 'E', 'F')
mass_2 = pd.Series([11, 13, 15, 20, 23, 26], index = index)
print(mass_2)

benzene      80
acetone      56
toluene     111
pentane      36
ether        35
ethanol      78
methanol     65
dtype: int64
A    11
B    13
C    15
D    20
E    23
F    26
dtype: int64

In [8]:
table + mass_2

A          NaN
B          NaN
C          NaN
D          NaN
E          NaN
F          NaN
acetone    NaN
benzene    NaN
ethanol    NaN
ether      NaN
methanol   NaN
pentane    NaN
toluene    NaN
dtype: float64

### same indexes

In [ ]:

index = ('benzene', 'acetone', 'toluene', 'pentane', 'ether', 'ethanol', 'methanol')
table2 = pd.Series([70, 56, 111, 56, 35, 78, 65], index = index)
print(table)

index = ('benzene', 'acetone', 'toluene', 'pentane', 'ether', 'ethanol', 'methanol')
mass_1 = pd.Series([11, 13, 15, 20, 23, 26,30], index = index)
print(mass_1)

In [11]:
table2 + mass_1

benzene      81
acetone      69
toluene     126
pentane      76
ether        58
ethanol     104
methanol     95
dtype: int64

In [12]:
table2 * mass_1

benzene      770
acetone      728
toluene     1665
pentane     1120
ether        805
ethanol     2028
methanol    1950
dtype: int64

In [13]:
table2 - mass_1

benzene     59
acetone     43
toluene     96
pentane     36
ether       12
ethanol     52
methanol    35
dtype: int64

In [14]:
###Q-3 Write a Pandas program to compare the elements of the two Pandas Series.
## Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

num_1 = pd.Series([2, 4, 6, 8, 10])
num_2 = pd.Series([1, 3, 5, 7, 10])
print(num_1)
print(num_2)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64

In [16]:
print(num_1==num_2)
print(num_1>=num_2)
print(num_1<num_2)

0    False
1    False
2    False
3    False
4     True
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [19]:
num_2 = pd.Series([1, 3, 5, 7, 10])
num_2.dtypes

dtype('int64')

In [34]:
### Q-5.Write a function to change the data type of given a column or a Series. 
##Function takes series and data type as input, returns the converted series

def Change_dtype(num_2):
    return num_2.astype('int32')

con_series=Change_dtype(num_2)
con_series

0     1
1     3
2     5
3     7
4    10
dtype: int32

In [35]:
###`Q-6` Find top 10 most run getter from the series.

batman_run = pd.read_csv("E:\\code\\batsman_runs_ipl.csv")
batman_run

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [43]:
batman_run.sort_values(['batsman_run'], ascending=False)

           batter  batsman_run
569       V Kohli         6634
462      S Dhawan         6244
130     DA Warner         5883
430     RG Sharma         5881
493      SK Raina         5536
..            ...          ...
512   SS Cottrell            0
63   Abdur Razzak            0
65     Akash Deep            0
562        U Kaul            0
600    Yash Dayal            0

[605 rows x 2 columns]

In [56]:
### Q No of players having runs above 3000

batman_run[batman_run['batsman_run']>3000].shape[0]

20

In [64]:
###`Q-8` No of players having runs above mean value?

mean=batman_run['batsman_run'].mean()
mean

np.float64(464.42809917355373)

In [65]:
batman_run[batman_run['batsman_run']>mean].shape[0]

128